#server.port=8002
#spring.application.name=servicio-items

#servicio-productos.ribbon.listOfServers=localhost:8001,localhost:9001
servicio-productos:
  ribbon:
    listOfServers: http://localhost:8001,localhost:9001